-- Rode no SQL Editor do Supabase (uma vez).
-- Cadastra pares de matérias que podem acontecer ao mesmo tempo na mesma turma.

alter table public.tb_curso
  add column if not exists turno_compartilhado boolean not null default false;

create table if not exists public.tb_curso_aula_geminada (
  id bigint generated by default as identity primary key,
  id_curso bigint not null references public.tb_curso(id) on delete cascade,
  id_materia_a bigint not null references public.tb_materia(id) on delete cascade,
  id_materia_b bigint not null references public.tb_materia(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint tb_curso_aula_geminada_materias_diferentes
    check (id_materia_a <> id_materia_b),
  constraint tb_curso_aula_geminada_ordem
    check (id_materia_a < id_materia_b),
  constraint tb_curso_aula_geminada_unica
    unique (id_curso, id_materia_a, id_materia_b)
);
